update

diff --git a/templatetator/bash/template b/templatetator/bash/template
--- a/templatetator/bash/template
+++ b/templatetator/bash/template
@@ -1,25 +1,32 @@
-NAME="SCRIPTNAME"
-VERSION="0.001"
-AUTHOR="budRich"
-CONTACT='robstenklippa@gmail.com'
-CREATED="THISDATE"
-UPDATED="THISDATE"
+#!/usr/bin/env bash
+
+__name="SCRIPTNAME"
+__version="0.001"
+__author="budRich"
+__contact='robstenklippa@gmail.com'
+__created="THISDATE"
+__updated="THISDATE"
 
 main(){
-  while getopts :vh option; do
-    case "${option}" in
-      v) printf '%s\n' \
-           "$NAME - version: $VERSION" \
-           "updated: $UPDATED by $AUTHOR"
-         exit ;;
-      h|*) printinfo && exit ;;
+
+  eval set -- "$(getopt --name "$__name" \
+    --options vh:: \
+    --longoptions version,help::,debug: \
+    -- "$@"
+  )"
+
+  while true; do
+    case "$1" in
+      -v | --version ) printinfo version ; exit ;;
+      -h | --help ) printinfo "${2:-}" ; exit ;;
+      -- ) shift; break ;;
+      * ) break ;;
     esac
   done
 }
 
 printinfo(){
-about='
-`SCRIPTNAME` - Short description
+about='`"SCRIPTNAME"` - Short description
 
 SYNOPSIS
 --------
@@ -74,7 +81,7 @@ Sublime Text
 '
 
 bouthead="
-${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
+${__name^^} 1 ${__created} Linux \"User Manuals\"
 =======================================
 
 NAME
@@ -85,7 +92,7 @@ boutfoot="
 AUTHOR
 ------
 
-${AUTHOR} <${CONTACT}>
+${__author} <${__contact}>
 <https://budrich.github.io>
 
 SEE ALSO
@@ -97,15 +104,27 @@ http://www.schweikhardt.net/man_page_howto.html)
 
 
   case "$1" in
-    m ) printf '%s' "${about}" ;;
+    # print version info to stdout
+    version )
+      printf '%s\n' \
+        "$__name - version: $__version" \
+        "updated: $__updated by $__author"
+      exit
+      ;;
+    # print help in markdown format to stdout
+    md ) printf '%s' "# ${about}" ;;
+
+    # print help in markdown format to README.md
+    mdg ) printf '%s' "# ${about}" > "${__dir}/README.md" ;;
     
-    f ) 
-      printf '%s' "${bouthead}"
-      printf '%s' "${about}"
-      printf '%s' "${boutfoot}"
+    # print help in troff format to __dir/__name.1
+    man ) 
+      printf '%s' "${bouthead}" "${about}" "${boutfoot}" \
+      | go-md2man > "${__dir}/${__name}.1"
     ;;
 
-    ''|* ) 
+    # print help to stdout
+    * ) 
       printf '%s' "${about}" | awk '
          BEGIN{ind=0}
          $0~/^```/{
@@ -123,15 +142,22 @@ http://www.schweikhardt.net/man_page_howto.html)
   esac
 }
 
-ERR(){ >&2 echo $@ ; }
-ERX(){ >&2 echo $@ && exit 1 ; }
+ERR(){ >&2 echo "[WARNING]" "$*"; }
+ERX(){ >&2 echo "[ERROR]" "$*" && exit 1 ; }
 
-if [ "$1" = "md" ]; then
-  printinfo m
-  exit
-elif [ "$1" = "man" ]; then
-  printinfo f
-  exit
-else
-  main "${@}"
-fi
+init(){
+  set -o errexit
+  set -o pipefail
+  set -o nounset
+  # set -o xtrace
+
+  __source="$(readlink -f "${BASH_SOURCE[0]}")"
+  __dir="$(cd "$(dirname "${__source}")" && pwd)"
+  __file="${__dir}/$(basename "${__source}")"
+  __base="$(basename ${__file} .sh)"
+  __root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app
+}
+
+init
+eval __lastarg="\${$#}"
+main "${@}"
